/*---------------------------------------------------------------------------------
-                                                                                 -
-                                                                                 -
-    Author: Cristian Martinez                                                    -
-                                                                                 -
-    file name: guessinggame.c                                                    -
-                                                                                 -
-                                                                                 -
-    Usage: A random number is chosen between 1 and 100.                          -
-            The player is given a set of bounds and                              -
-            must choose a number between them.                                   -
-            If the player chooses the correct number, he wins.                   -
-            Otherwise, the bounds are adjusted to reflect                        -
-            the player's guess and the game continues.                           -
-                                                                                 -
-   Restrictions:  The random number is generated by the statement                -
-                  rand() % 100. Because rand() returns a number                  -
-                   0 <= rand() <= maxint this slightly favors                    -
-                   the lower numbers.                                            -
----------------------------------------------------------------------------------*/

/*-----------------------------------------------------------------*\
    * Include section  *
\*-----------------------------------------------------------------*/

#include <stdio.h>  /*Standar library I/O */
#include <stdlib.h> /*Include rand()*/
#include <time.h>

/*-----------------------------------------------------------------*\
    * DEFINE AND MACROS (use ALL_CAPS separated by underscore)  *
\*-----------------------------------------------------------------*/

/*-----------------------------------------------------------------*\
    * Typedef Section  *
\*-----------------------------------------------------------------*/

/*-----------------------------------------------------------------*\
    * Prototipe functions
\*-----------------------------------------------------------------*/

/*------------------------------------------------------------------*\
    * Global variables
\*------------------------------------------------------------------*/

/*>>>>>>>>>>>>>>>>>>>>>>> Major section header <<<<<<<<<<<<<<<<<<<<<*/

int main(void)
{
    /* Initialize variables for loop */
    int number_to_guess;   /* random number to be guessed */
    int low_limit = 0;     /* current lower limit of player's range */
    int high_limit = 100;  /* current upper limit of player's range */
    int attemps = 0;       /* number of times player guessed */
    int player_number = 0; /* number gotten from the player */

    srand(time(NULL)); /* // Seed the random number generator with the current time */

    number_to_guess = (rand() % 100) + 1;

    printf("## Number to guess: %d\n", number_to_guess);

    while (1)
    {
        /* tell user what the bounds are and get his guess */
        printf("Bounds: %d - %d\n", low_limit, high_limit);
        printf("Attemps[%d]\n", attemps);

        ++attemps;

        printf("Enter a guess: ");
        scanf("%d", &player_number);

        if (player_number == number_to_guess)
        {
            printf("You got it!\n");
            break;
        }

        if (player_number < number_to_guess)
        {
            printf("Guess higher!\n");
            low_limit = player_number;
        }
        else
        {
            printf("Guess lower!\n");
            high_limit = player_number;
        }
    }

    return 0;
}